### PR TITLE
Fixed initial test errors

### PR DESCRIPTION
**Pull request by mikeclark**
added local php server start for testing with guzzle; fixed content-type tests;

process from starting to contribute:

1. git clone
2. copy .env.example to .env
3. ./vendor/phpunit/phpunit/phphunit

All tests should pass

Note:  I used port 8890 - not sure this is good or bad.  I didn't want to use 8080 or 8888 since you could already be using that for manual development testing

### CODE REVIEW

**Comment by RogerCreasy** [comment]
I pulled your branch, switched to it, did Composer install (to pull in the new dependencies)
When I run phpunit - I get cURL errors that the connection was refused.

I'll investigate further later. It could be an issue with my system setup

**Comment by mikeclark** [comment]
How many curl errors?  looks like it's having trouble initiating and shutting down the server the first time through - I clone to another folder and tested - when first running it, I got a single curl error but then on the next run everything passed because the server was still running from previous test!

I'll dig into it.

**Comment by RogerCreasy** [comment]
I did confirm that I can run the PHP built in server locally using port 8890
All works./
I have a couple of other PRs to merge. You may have to rebase.

**Comment by RogerCreasy** [comment]
Great! works for me too.
Thanks for the help on this. Hopefully we can get other tests added now.
Sorry for the delayed response.

**Pull request merged**
