### PR TITLE
Fix user autoincrement id

### PR DESCRIPTION
**Pull request by izambl**

### CODE REVIEW

**Comment by RogerCreasy** [comment]
Thanks for looking at this issue!
I tried your code. Creating a new user still does not add the ID field for me.
I tested running under Linux and nginx, with the default SQLite DB.

**Comment by RogerCreasy** [comment]
Sorry for the delay.
I get three errors: 
    [Doctrine\DBAL\Exception\DriverException]               
  An exception occurred in driver: could not find driver

[Doctrine\DBAL\Driver\PDOException]  
  could not find driver

[PDOException]         
  could not find driver

**Comment by izambl** [comment]
That's the problem, the migration is not running and the change is not beign applied.

I had to set the env variables with the database type and adapter to get them to run

**Comment by RogerCreasy** [comment]
I am not sure what you mean. I do have the DB type set, and the driver (both like .env.example).

**Comment by RogerCreasy** [comment]
@izambl I apologize for being silent. I have been pulled in other directions the past few days.
Are you still looking at this?

**Comment by RogerCreasy** [comment]
@izambl I am sorry it took me so long to get back to this. I did merge.
Thanks again for your help. Please continue as a member of the community!

**Pull request merged**
